#!/usr/bin/env sh

if [ -n "$TMUX" ] ; then
    # tmux session running
    tmux split-window -h "nvim \"$*\""
else
    # Remove option --tab for new window
    xfce4-terminal --tab -e "nvim \"$*\""
fi
