#!/usr/bin/env bash

# different fuzy finders fzf | dmenu | gum filter

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
      find -L ~/ImpactKarma/ssh/ ~/ImpactKarma/ ~/ ~/Downloads/ ~/notes/ ~/scripts/ ~/.config/ /Users/  -mindepth 1 -maxdepth 1 -type d \
      | sed  's/\/home\/adelg/~/g'  \
      | fzf --height=20 --border=sharp -i --layout=reverse-list
    )
fi

if [[ -z $selected ]]; then
    exit 0
fi

dir=$(echo $selected | sed 's/~/\/home\/adelg/g' )
selected_name=$(basename "$dir" | tr . _)

# check if a session with the same name already exists
existingSession=$(tmux list-sessions -F '#S' | grep "^$selected_name$")

if [[ -z $TMUX ]]; then
    # not in tmux session
    if [[ -z $existingSession ]]; then
        # session does not exist
        tmux new-session -s $selected_name -c $dir
    else
        # session exists... attach to it
        tmux attach -t $selected_name
    fi
else
    # inside tmux session
    if [[ -z $existingSession ]]; then
        # session does not exist... create it
        tmux new-session -d -s $selected_name -c $dir
    fi
        # switch to the session
        tmux switch-client -t $selected_name
fi
