#!/usr/bin/env bash
#
# Script name: dm-docker-kill
# Description: Search for a running docker container to kill.
# Dependencies: dmenu, docker
# GitLab: https://github.com/adelgado0723/dmscripts
# Contributors: Derek Taylor, Andy Delgado

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.

set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi


# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
    docker ps | awk 'NR>1{print}' |  ${DMENU} "choose container to stop:" | awk '{system("echo stopping selection... && docker stop " $1 " &")}'
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main 
